website:
  url: "update_me"
  credentials:
    username: "update_me"
    password: "update_me"

api:
  url: "update_me"
  # This is a suboptimal way of storing to store sensitive information
  # in production grade project this key would be stored in AWS KMS or similar key vault
  key: