name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make init
          make sync

      - name: Code check
        run: |
          make check

      - name: Run tests
        run: |
          make test

      - name: Upload UI Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui_test_report
          path: reports/ui_test_report.html

      - name: Upload Load Test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: load_test_report
          path: reports/load_test_report.html
